Game.SelectMission("m2sd")
	Game.SetMissionStartCameraName("mission2camShape")
	Game.SetMissionStartMulticontName("mission2cam")
	Game.SetAnimatedCameraName("mission2camShape")
	Game.SetAnimCamMulticontName("mission2cam")

	Game.SetMissionResetPlayerOutCar("homer_start_alt","level1_carstart")
	Game.SetDynaLoadData("l1z1.p3d;l1r1.p3d;l1r7.p3d;")

	Game.UsePedGroup(0)

	Game.AddStage(0)
		Game.SetHUDIcon("simpsons")
		Game.SetStageMessageIndex(0)

		Game.SetMaxTraffic(2)

		Game.AddObjective("goto")
			Game.AddNPC("marge","m2_marge_sd")
			Game.SetDestination("m2_simpsonhouse_sd","carsphere")
			Game.SetCollectibleEffect("wrench_collect")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(1)
		Game.RESET_TO_HERE()

		Game.SetHUDIcon("simpsons")
		Game.SetStageMessageIndex(1)

		Game.AddObjective("interior")
			Game.AddNPC("marge","m2_marge_sd")
			Game.SetDestination("SimpsonsHouse","simp_mission_doorstar")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetHUDIcon("marage")
		Game.SetStageMessageIndex(2)

		Game.AddObjective("talkto")
			Game.AddNPC("marge","m2_marge_sd")
			Game.SetTalkToTarget("marge",0,0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.AddObjective("dialogue")
			Game.SetPresentationBitmap("art/frontend/dynaload/images/mis01_02.p3d")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.AddAmbientNpcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_thinking")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.SetDialogueInfo("homer","marge","neighbor",0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetStageMessageIndex(3)

		Game.AddObjective("gooutside")
			Game.SetDestination("outside_Simpsons_house_locator")

			Game.TurnGotoDialogOff()
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(4)
		Game.SetHUDIcon("ned")
		Game.SetStageMessageIndex(4)

		Game.AddObjective("talkto","neither")
			Game.AddNPC("ned","m2_ned_sd")
			Game.AddObjectiveNPCWaypoint("ned","ned_walk_1")
			Game.AddObjectiveNPCWaypoint("ned","ned_walk_2")
			Game.AddObjectiveNPCWaypoint("ned","ned_walk_3")
			Game.AddObjectiveNPCWaypoint("ned","ned_walk_2")
			Game.AddObjectiveNPCWaypoint("ned","ned_walk_1")

			Game.SetTalkToTarget("ned",0,0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.AddObjective("dialogue")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"npc_far")
			Game.SetConversationCam(1,"pc_near")
			Game.SetConversationCam(2,"npc_far")
			Game.SetConversationCam(3,"pc_near")
			Game.AddAmbientNpcAnimation("dialogue_open_arm_hand_gesture")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_thinking")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.SetConversationCam(3,"pc_far")
			Game.SetDialogueInfo("homer","ned","culprit",0)
			Game.SetDialoguePositions("m2_homer_ned","m2_ned_sd","mission2_carstart")
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()