Game.SelectMission("m6sd")
	Game.SetMissionStartCameraName("mission6camShape")
	Game.SetMissionStartMulticontName("mission6cam")
	Game.SetAnimatedCameraName("mission6camShape")
	Game.SetAnimCamMulticontName("mission6cam")

	Game.SetMissionResetPlayerOutCar("m6_homer_start","m6_carstart")
	Game.SetDynaLoadData("l1z3.p3d;l1r3.p3d;l1r2.p3d;")

	Game.UsePedGroup(3)

	Game.AddStage(1)
		Game.RESET_TO_HERE()

		Game.SetHUDIcon("grocery")
		Game.SetStageMessageIndex(1)

		Game.SetMaxTraffic(2)

		Game.AddStageVehicle("marge_v","m6_canyanaro_sd","NULL","EasyRace\\AI_5th.con")

		Game.AddObjective("goto")
			Game.AddNPC("marge","m6_marge_sd")

			Game.SetDestination("m6_locator_sd","carsphere")
			Game.SetCollectibleEffect("wrench_collect")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(5)
		Game.RESET_TO_HERE()

		Game.SetHUDIcon("marage")
		Game.SetStageMessageIndex(2)

		Game.AddObjective("talkto")
			Game.AddNPC("marge","m6_marge_sd")
			Game.AddObjectiveNPCWaypoint("marge","m6_marge_walk_2")
			Game.AddObjectiveNPCWaypoint("marge","m6_marge_walk_1")
			Game.SetTalkToTarget("marge",0,0.2)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.AddObjective("dialogue")
			Game.SetPresentationBitmap("art/frontend/dynaload/images/mis01_06.p3d")
			Game.AmbientAnimationRandomize(1,0)
			Game.AmbientAnimationRandomize(0,0)
			Game.SetConversationCam(0,"pc_near")
			Game.SetConversationCam(1,"npc_far")
			Game.SetConversationCam(2,"pc_near")
			Game.SetConversationCam(3,"npc_near")
			Game.SetConversationCam(4,"pc_far")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_cross_arms")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientNpcAnimation("dialogue_shaking_fist")
			Game.AddAmbientNpcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_hands_in_air")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_yes")
			Game.AddAmbientPcAnimation("none")
			Game.AddAmbientPcAnimation("dialogue_scratch_head")
			Game.SetCamBestSide("m6_end")
			Game.SetDialogueInfo("homer","marge","violent",0)
			Game.SetDialoguePositions("m6_homer","m6_homer_start","m6_marge_walk_2")
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()